version: 1.0.0
requiredRoles:
- admin
- database_admin
features:
  created: 2026-01-10
subCategory:
  name: SQLite
  order: 3
name: SQLite Manager
routePrefix: /apps/sqlitemanager
author: test
description: SQLite database file management
enabled: true
parentCategory:
  id: databases
  name: Databases
  description: Database administration and monitoring
  icon: database
  order: 3

