version: 1.0.0
requiredRoles:
- admin
- database_admin
features:
  created: 2026-01-10
subCategory:
  name: SQL Server
  order: 4
name: SQL Server Manager
routePrefix: /apps/sqlservermanager
author: test
description: Microsoft SQL Server administration
enabled: true
parentCategory:
  id: databases
  name: Databases
  description: Database administration and monitoring
  icon: database
  order: 3

