<#
.SYNOPSIS
    Converts a source image into a standard set of favicons and generates an HTML file for them.
.DESCRIPTION
    This script takes a source image and a base name to generate multiple favicon formats (.ico, .png, .svg)
    in various resolutions. It places the generated files in '/public/icon/' and creates a 'favicon.html'
    file with the optimal HTML <link> tags for web implementation.

    Generated PNG Sizes: 16x16, 32x32, 48x48, 180x180, 192x192, 512x512.
.PARAMETER Name
    The base name for the output icon files (e.g., 'my-app').
.PARAMETER Path
    The full path to the source image file (e.g., C:\temp\logo.png).
.EXAMPLE
    PS > .\makefavicon.ps1 -Name "my-app" -Path "C:\Users\Me\Pictures\logo.png"

    This command will generate icons like 'my-app_16x16.png', 'favicon.ico', etc.,
    in the 'e:\sc\git\PsWebHost\public\icon' directory and create 'favicon.html' there.
#>
param(
    [Parameter(Mandatory = $true)]
    [string]$Name,

    [Parameter(Mandatory = $true)]
    [string]$Path,

    # The script is in /system, so the output dir is relative to its parent
    $outputDir = (Join-Path -Path (Split-Path $PSScriptRoot) "\public\icon")
)

try {
    
    If (!(Test-Path $outputDir)) {mkdir $outputDir}
    # Ensure the System.Drawing assembly is available for image manipulation
    Add-Type -AssemblyName System.Drawing | Out-Null

    # --- 1. Setup Paths and Validate Inputs ---
    if (-not (Test-Path -Path $Path -PathType Leaf)) {
        Write-Error "Source image file not found at: $Path"
        return
    }

    # Create the output directory if it doesn't exist
    if (-not (Test-Path -Path $outputDir)) {
        Write-Host "Creating output directory: $outputDir"
        New-Item -ItemType Directory -Force -Path $outputDir | Out-Null
    }

    Write-Host "Processing source image: $Path"
    $sourceImage = [System.Drawing.Image]::FromFile($Path)

    # --- 2. Generate PNG Icons for Various Resolutions ---
    $pngSizes = @(16, 32, 48, 180, 192, 512)
    $generatedPngFiles = @()

    foreach ($size in $pngSizes) {
        $outputPath = Join-Path -Path $outputDir -ChildPath "${Name}_${size}x${size}.png"
        Write-Host "Generating ${size}x${size} PNG: $outputPath"

        $resizedImage = New-Object System.Drawing.Bitmap($size, $size)
        $graphics = [System.Drawing.Graphics]::FromImage($resizedImage)

        # Use high-quality settings for resizing
        $graphics.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
        $graphics.CompositingQuality = [System.Drawing.Drawing2D.CompositingQuality]::HighQuality
        $graphics.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::HighQuality

        $graphics.DrawImage($sourceImage, 0, 0, $size, $size)

        $resizedImage.Save($outputPath, [System.Drawing.Imaging.ImageFormat]::Png)

        $graphics.Dispose()
        $resizedImage.Dispose()
        $generatedPngFiles += $outputPath
    }

    # --- 3. Generate favicon.ico ---
    $icoPath = Join-Path -Path $outputDir -ChildPath "$Name`_favicon.ico"
    Write-Host "Generating favicon.ico (32x32): $icoPath"
    $icoBitmap = New-Object System.Drawing.Bitmap($sourceImage, 32, 32)
    $icoBitmap.Save($icoPath, [System.Drawing.Imaging.ImageFormat]::Icon)
    $icoBitmap.Dispose()

    # --- 4. Handle SVG ---
    $svgHref = $null
    if ($Path -like '*.svg') {
        $svgDestPath = Join-Path -Path $outputDir -ChildPath "${Name}.svg"
        Copy-Item -Path $Path -Destination $svgDestPath
        $svgHref = "/icon/${Name}.svg"
        Write-Host "Copied SVG source to: $svgDestPath"
    }

    # --- 5. Generate favicon.html ---
    $htmlPath = Join-Path -Path $outputDir -ChildPath "favicon.html"
    Write-Host "Generating HTML link tags at: $htmlPath"

    $htmlContent = @"
<!--
  Generated by makefavicon.ps1
  Optimal order for favicon link tags.
-->

<!-- Universal .ico for broadest compatibility -->
<link rel="icon" href="/icon/${Name}_favicon.ico" sizes="any">

<!-- SVG icon for modern browsers that prefer scalable graphics -->
"@
    if ($svgHref) {
        $htmlContent += "`n<link rel=`"icon`" href=`"$svgHref`" type=`"image/svg+xml`">`n"
    }

    $htmlContent += @"
<!-- Apple Touch Icon for iOS home screens (no 'sizes' attribute needed) -->
<link rel="apple-touch-icon" href="/icon/${Name}_180x180.png">

<!-- High-resolution PNGs for modern browsers, PWAs, and Android -->
<link rel="icon" type="image/png" sizes="512x512" href="/icon/${Name}_512x512.png">
<link rel="icon" type="image/png" sizes="192x192" href="/icon/${Name}_192x192.png">

<!-- PNG for Windows desktop shortcuts -->
<link rel="icon" type="image/png" sizes="48x48" href="/icon/${Name}_48x48.png">

<!-- Standard resolution PNG for browser tabs -->
<link rel="icon" type="image/png" sizes="32x32" href="/icon/${Name}_32x32.png">

<!-- Legacy PNG for older browsers -->
<link rel="icon" type="image/png" sizes="16x16" href="/icon/${Name}_16x16.png">
"@

    $htmlContent | Out-File -FilePath $htmlPath -Encoding utf8

    Write-Host "`nFavicon generation complete."
    Write-Host "Files are located in: $outputDir"

}
catch {
    Write-Error "An error occurred during favicon generation: $_"
}
finally {
    # --- 6. Clean up ---
    if ($sourceImage) {
        $sourceImage.Dispose()
    }
}
